name: Pacifica-Core
version: ${version}
main: com.districtx.pacificacore.PacificaCore
api-version: '1.20'
author: DistrictX Developers Officials
depend:
  - Vault
softdepend:
  - Pacifica-II
  - Pacifica-LootSystem
  - PlaceholderAPI
commands:
  diamond:
    description: Show your Diamond Currency balance
    aliases: [dias, diamonds, dc]
    permission: pacifica.core.command.diamond
  bal:
    description: Show a server balance
    aliases: [balance]
    permission: pacifica.core.command.balance
  core:
    description: Manage Pacifica-Core currency
    aliases: [dmdadmin]
    permission: pacifica.core.admin.reload
  bm:
    description: Open the Black Market
    aliases: [blackmarket]
    permission: pacifica.core.command.blackmarket
  bmadmin:
    description: Manage Black Market item categories
    permission: blackmarket.admin.category
  level:
    description: View your Pacifica Player Level and experience
    aliases: [levels, playerlevel]
    permission: pacifica.level.command
  leveladmin:
    description: Manage Pacifica Player Levels and experience
permissions:
  pacifica.core.command.diamond:
    default: true
  pacifica.core.command.balance:
    default: true
  pacifica.core.command.balance.others:
    default: op
  pacifica.core.admin.reload:
    default: op
  pacifica.core.admin.dgive:
    default: op
  pacifica.core.admin.bgive:
    default: op
  pacifica.core.admin.reset:
    default: op
  pacifica.core.admin.get:
    default: op
  pacifica.core.admin.set:
    default: op
  pacifica.core.command.blackmarket:
    default: true
  blackmarket.admin.category:
    default: op
  pacifica.level.command:
    default: true
  pacifica.level.admin:
    default: op
    children:
      pacifica.level.set: true
      pacifica.level.addxp: true
      pacifica.level.setxp: true
      pacifica.level.removexp: true
      pacifica.level.info: true
  pacifica.level.set:
    default: op
  pacifica.level.addxp:
    default: op
  pacifica.level.setxp:
    default: op
  pacifica.level.removexp:
    default: op
  pacifica.level.info:
    default: op